# Site settings
title: Blockchain for Developer
description: "Blockchain development technologies."
baseurl: "/blockchain-for-developer" 
url: "https://github.com/bitflying/bitflying.github.io/blockchain-for-developer" 
tagline: A basic technology guide to Blockchain

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title

# Plugins
plugins: [jekyll-paginate]